name: Node Js CI

on:
  push:
    branches:
      - main
      - develop

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo variable
        run: |
          echo "Token: ${{ vars.TOKEN }}"

  build-and-tests:
    runs-on: ubuntu-latest
    needs: pre-build
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm ci

      - name: Build
        run: |
          npm run build --if-present

      - name: Unit Tests
        run: |
          npm run test:unit

      - name: Test e2e
        run: |
          npx playwright install --with-deps
          npm run test:integration

      #- name: Report Coverage
        # Set if: always() to also generate the report if tests are failing
        # Only works if you set `reportOnFailure: true` in your vite config as specified above
        #if: always()
        #uses:  davelosert/vitest-coverage-report-action@v2

  bump-version:
    runs-on: ubuntu-latest
    needs: build-and-tests
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Bump Version develop
        if: github.ref == 'refs/heads/develop'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version-type: 'patch'
          target-branch: 'develop'

      - name: Bump Version master
        if: github.ref == 'refs/heads/main'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version-type: 'patch'
          target-branch: 'main'

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: bump-version
    permissions:
      contents: write

    steps:
      - name: Docker Build and push
        run: |
          echo "Building and pushing the docker image"

  deploy:
    needs: docker-build-and-push
    uses: ./.github/workflows/argo.yml
    with:
      cluster: 'gcp-dev'

