name: Node Js CI

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm ci

      - name: Test
        run: |
          npx playwright install --with-deps
          npm run build --if-present
          npm test

  bump-version:
    runs-on: ubuntu-latest
    needs: build-and-tests
    permissions:
      contents: write

    steps:
      - name: Bump Version develop
        if: github.ref == 'refs/heads/develop'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version-type: 'patch'
          target-branch: 'develop'

      - name: Bump Version master
        if: github.ref == 'refs/heads/main'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version-type: 'patch'
          target-branch: 'main'

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: bump-version
    permissions:
      contents: write

    steps:
      - name: Docker Build and push
        run: |
          echo "Building and pushing the docker image"

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build-and-push
    permissions:
      contents: write

    steps:
      - name: Deploy to Development
        if: github.ref == 'refs/heads/develop'
        run: |
          echo "Deploying the code to Development"
          echo "ArgoCD Password: ${{ secrets.ARGOCD_PASSWD }}"
          chmod +x scripts/sync.sh
          ./scripts/sync.sh ${{ secrets.ARGOCD_PASSWD }} svblog

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploying the code to Production"
          echo "ArgoCD Password: ${{ secrets.ARGOCD_PASSWD }}"
          chmod +x scripts/sync.sh
          ./scripts/sync.sh ${{ secrets.ARGOCD_PASSWD }} svblog
