name: Node Js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Bump Version
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version-type: 'patch'
      
      - name: Update Resources
        run: |
          echo "Updating the resources"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci

      - name: Test
        run: |
          npx playwright install --with-deps
          npm run build --if-present
          npm test

      - name: Docker Build and push
        run: |
          echo "Building and pushing the docker image"

      - name: Deploy
        run: |
          echo "Deploying the code"
          echo "ArgoCD Password: ${{ secrets.ARGOCD_PASSWD }}"
          chmod +x scripts/sync.sh
          ./scripts/sync.sh ${{ secrets.ARGOCD_PASSWD }} svblog
